apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: test-umbrella
  namespace: fleet-local
spec:
  repo: https://github.com/atoy3731/test-fleet.git
  targets:
  - clusterSelector:
      matchExpressions:
      - key: provider.cattle.io
        operator: NotIn
        values:
        - harvester
  paths:
  - ./configs
