apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: test-gitrepo
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/test-fleet.git
  targets:
  - clusterSelector: {}
  paths:
  - ./configs
